### ISSUE TITLE
Ideas for enhancements

### ISSUE THREAD

**Issue by swrobel** [dbalatero/capybara-chromedriver-logger#2]
This is very cool! I've been playing around with getting this same info to show in my tests, but you seem to have done a nicer job of packaging & presenting it. Glad I found this before I got too far in! Here are some ideas for improvements I have from what I've been working on:

1. Only show if the test failed. This seems to work in my testing, but there might be a better way to do this:
```ruby
config.after(:each, type: :system) do |example|
  if example&.exception
    Capybara::Chromedriver::Logger::TestHooks.after_example!
  end
end
```

2. If only showing on failure, print the js logs after the expectation message. This seems a bit tricker but I feel like there must be a way to do this. It will make it a lot easier to associate the js logs with the test that failed. Any ideas here?

3. If the above isn't possible, at least print the test name with the js logs. I've been doing the following
```ruby
config.after(:each, type: :system) do |example|
  if example&.exception
    logs = page.driver.browser.manage.logs.get(:browser)
    errors = logs&.select { |l| l.level == 'SEVERE' }
    if errors.any?
      puts "\njs errors in #{example.example_group_instance.method_name}:".red
      errors.each { |e| puts "  #{e.message.gsub('\n', "\n").gsub('\u003C', "\u003C")}".red }
    end
  end
end
end
```

4. Figure out how to get Chrome to give logs with the filename & line:column from the original sourcefile by using sourcemaps. I think this is a Chrome bug and have [opened an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=812153), please star if you think it's a bug as well.

**Comment by dbalatero** [comment]
@swrobel 

> Only show if the test failed. This seems to work in my testing, but there might be a better way to do this:

Totally agree! I started off with showing everything because I wanted to address incidental logs. I'd like this to be a config option that can be flipped on or off.

> If only showing on failure, print the js logs after the expectation message. This seems a bit tricker but I feel like there must be a way to do this. It will make it a lot easier to associate the js logs with the test that failed. Any ideas here?

Nope but I agree with this as a feature enhancement as well. I think it can be done. We'll have to dig into rspec a bit.

> Figure out how to get Chrome to give logs with the filename & line:column from the original sourcefile by using sourcemaps. I think this is a Chrome bug and have opened an issue, please star if you think it's a bug as well.

Yes please, with full stacktrace! One possible option is to inject a custom `window.onerror` handler into the page. This would require re-injecting it every time `#visit` is called or the page URL changes though. Poltergeist had a great feature for including custom injected css/js into every phantomjs session which I really appreciated. There might be a Chrome extension for injecting stuff into the page, and the extension can be included in the `chrome_args` and loaded, as one cheap way to get there.

Fixing the Chrome bug would be ideal too :)

**Comment by dbalatero** [comment]
@swrobel Would you open issues for these ones and we can start looking into them?

**Comment by swrobel** [comment]
Apologies for the lack of movement on my end - I've been swamped @ work. I did open [an issue](https://github.com/SeleniumHQ/selenium/issues/5567) with Selenium based on the feedback on my Chromium issue (linked above) indicating that it should be possible to pull sourcemap data using the remote protocol.

**Comment by dbalatero** [comment]
@swrobel Awesome. It would be great to get the _full_ stacktrace as sometimes it is contextually relevant to get it too. Not sure if the Chromium hook for sourcemaps can pull that out?

**Comment by dbalatero** [comment]
I'm going to close this for now!
